import reflex as rx

links = [
    rx.link("Home", href="http://localhost:3000"),
    rx.link("GAN Training Results", href="http://localhost:3000/about"),
    rx.link("Results", href="http://localhost:3000/results"),
    rx.link("Generated", href="http://localhost:3000/generated"),


]


def generated() -> rx.Component:
    return rx.fragment(
        rx.vstack(
            rx.heading("Generated Images", font_size="2em", color="#756AEE"),
            rx.box(
                rx.text("Here are some of the images generated by the GAN model, all these images are 64x64 pixels only as higher resolution images take more training time and higher computational resources.", padding_bottom="2em"),
                rx.image(
                    src="image_test.jpg",
                    width="100%",
                    height="100%",
                    #padding="0.5em",
                    flex="1 1 auto",
                    border_radius="0.5rem",
                    ),
                rx.spacer(padding="1.0rem"),
                rx.image(
                    src="image_test1.jpg",
                    width="100%",
                    height="100%",
                    #padding="0.5em",
                    flex="1 1 auto",
                    border_radius="0.5rem",
                    ),
                rx.spacer(padding="1.0rem"),
                 rx.image(
                    src="image_test2.jpg",
                    width="100%",
                    height="100%",
                    #padding="0.5em",
                    flex="1 1 auto",
                    border_radius="0.5rem",
                    ),
                rx.spacer(padding="1.0rem"),
                rx.image(
                    src="image_test3.jpg",
                    width="100%",
                    height="100%",
                    #padding="0.5em",
                    flex="1 1 auto",
                    border_radius="0.5rem",
                    ),
                rx.spacer(padding="1.0rem"),
                rx.image(
                    src="image_test4.jpg",
                    width="100%",
                    height="100%",
                    #padding="0.5em",
                    flex="1 1 auto",
                    border_radius="0.5rem",
                    ),
                rx.spacer(padding="1.0rem"),
                rx.image(
                    src="image_test5.jpg",
                    width="100%",
                    height="100%",
                    #padding="0.5em",
                    flex="1 1 auto",
                    border_radius="0.5rem",
                    ),
                border_radius="15px",
                border_width="thick",
                padding="1em",
                border_color="#756AEE",
                font_size="0.7em",
                width="50%",
            ),
            spacing="1.5em",
            font_size="2em",
            padding_top="10%",
        ),



        rx.center(
            rx.flex(
                *links,
                # Size
                max_width="1280px",
                width="clamp(288px, 80%, 640px)",
                height="clamp(32px, 50%, 256px)",
                # Flex
                gap="1.0rem",
                padding="1.0rem",
                align_items="center",
                justify="space-evenly",
                # Background
                border_radius="256px",
                backdrop_filter="blur(16px)",
                background_color="rgba(255, 255, 255, 0.15)",
                # Font
                font_weight="600",
                font_size="clamp(16px, 2.5svh, 256px)",
                
            ),
        #rx.color_mode_button(rx.color_mode_icon(), float="right"),
        # Position
        top="0.0",
        z_index="5",
        margin="0.0",
        padding="0.0",
        position="fixed",
        # Size
        width="100svw",
        height="12.5svh",
        # Config
        border_radius="1em",
        box_shadow="rgba(151, 65, 252, 0.8) 0 15px 30px -10px",
        background_color="#756AEE",
    
        ),



    )